from __future__ import annotations
from typing import Mapping, Sequence

__version__: str

class RustyAltoError(RuntimeError): ...
class UnsupportedOperationError(RustyAltoError): ...
class StateOwnerError(RustyAltoError): ...

class State:
    @property
    def kind(self) -> str: ...
    @property
    def id(self) -> int | None: ...
    @property
    def start(self) -> int | None: ...
    @property
    def end(self) -> int | None: ...
    def components(self) -> list[State]: ...

class Tree:
    def __init__(self, label: str, children: Sequence[Tree] = ...) -> None: ...
    @property
    def label(self) -> str: ...
    @property
    def children(self) -> list[Tree]: ...

class Signature:
    @staticmethod
    def from_symbols(symbols: Sequence[tuple[str, int]]) -> Signature: ...
    def symbols(self) -> list[tuple[int, str, int]]: ...
    def id(self, name: str) -> int | None: ...
    def name(self, symbol: int) -> str: ...
    def arity(self, symbol: int) -> int: ...

class Homomorphism:
    @staticmethod
    def from_terms(
        source: Signature, target: Signature, terms: Mapping[int, Tree]
    ) -> Homomorphism: ...
    @property
    def source_signature(self) -> Signature: ...
    @property
    def target_signature(self) -> Signature: ...

class WeightedTree:
    @property
    def tree(self) -> Tree: ...
    @property
    def weight(self) -> float: ...
    @property
    def score(self) -> float: ...

class Automaton:
    @property
    def signature(self) -> Signature: ...
    @property
    def is_deterministic(self) -> bool: ...
    @property
    def has_state_universe(self) -> bool: ...
    @property
    def is_top_down(self) -> bool: ...
    @property
    def is_indexed(self) -> bool: ...
    @property
    def is_condensed(self) -> bool: ...
    def step(self, symbol: str | int, children: Sequence[State]) -> list[State]: ...
    def step_deterministic(
        self, symbol: str | int, children: Sequence[State]
    ) -> State | None: ...
    def is_accepting(self, state: State) -> bool: ...
    def states(self) -> list[State]: ...
    def initial_states(self) -> list[State]: ...
    def rules_for_parent(self, parent: State) -> list[tuple[int, list[State]]]: ...
    def rules_for_child(
        self, symbol: str | int, position: int, state: State
    ) -> list[tuple[list[State], State]]: ...
    def condensed_rules(
        self,
    ) -> list[tuple[list[State], list[int], State]]: ...
    def run(self, tree: Tree) -> list[State]: ...
    def accepts(self, tree: Tree) -> bool: ...
    def rules(self) -> list[tuple[int, list[int], int, float]]: ...
    def viterbi(self) -> WeightedTree | None: ...
    def k_best(self, limit: int = ...) -> list[WeightedTree]: ...
    def language_cardinality(self) -> tuple[str, int | None]: ...
    def product(self, other: Automaton) -> Automaton: ...
    def determinize(self) -> Automaton: ...
    def map_symbols(
        self, signature: Signature, mapping: Mapping[int, int]
    ) -> Automaton: ...
    def inverse_homomorphism(self, homomorphism: Homomorphism) -> Automaton: ...
    def materialize(
        self, alphabet: Sequence[tuple[int, int]] | None = ...
    ) -> tuple[Automaton, list[State]]: ...

class AutomatonBuilder:
    def add_state(self, name: str, accepting: bool = ...) -> int: ...
    def add_rule(
        self,
        symbol: str,
        children: Sequence[str],
        parent: str,
        weight: float = ...,
    ) -> None: ...
    def build(self) -> Automaton: ...

def load_automaton(path: str) -> Automaton: ...

class StringAlgebra:
    def parse(self, text: str) -> list[str]: ...
    def decompose(self, text: str) -> Automaton: ...

class TagStringAlgebra:
    def parse(self, text: str) -> list[str]: ...
    def decompose(self, text: str) -> Automaton: ...

class TagTreeAlgebra:
    def __init__(self, signature: Signature, with_arities: bool = ...) -> None: ...
    def decompose(self, text: str) -> Automaton: ...

class BinarizingTagTreeAlgebra:
    def __init__(self, signature: Signature, with_arities: bool = ...) -> None: ...
    def decompose(self, text: str) -> Automaton: ...

class FeatureStructure:
    @staticmethod
    def parse(text: str) -> FeatureStructure: ...
    def unify(self, other: FeatureStructure) -> FeatureStructure | None: ...
    def project(self, attribute: str) -> FeatureStructure | None: ...

class FeatureStructureAlgebra:
    def parse(self, text: str) -> FeatureStructure: ...

class InterpretationValue:
    @property
    def interpretation(self) -> str: ...
    @property
    def text(self) -> str: ...

class ParseControl:
    def cancel(self) -> None: ...
    @property
    def is_cancelled(self) -> bool: ...

class Interpretation:
    @property
    def name(self) -> str: ...
    @property
    def class_name(self) -> str: ...
    @property
    def is_inputable(self) -> bool: ...
    @property
    def signature(self) -> Signature: ...
    def parse(self, text: str) -> InterpretationValue: ...
    def decompose(self, text: str) -> Automaton: ...

class Irtg:
    @staticmethod
    def load(path: str) -> Irtg: ...
    @staticmethod
    def from_string(text: str) -> Irtg: ...
    @property
    def grammar(self) -> Automaton: ...
    def interpretations(self) -> list[Interpretation]: ...
    def interpretation(self, name: str) -> Interpretation: ...
    def parse(
        self,
        inputs: Mapping[str, str | InterpretationValue],
        strategy: str = ...,
        control: ParseControl | None = ...,
    ) -> ParseChart: ...
    def best(
        self, inputs: Mapping[str, str | InterpretationValue], strategy: str = ...
    ) -> Derivation | None: ...

class ParseChart:
    @property
    def automaton(self) -> Automaton: ...
    @property
    def state_parts(self) -> list[list[str]]: ...
    @property
    def stats(self) -> list[tuple[int, int, int, int]]: ...
    def best(self) -> Derivation | None: ...

class Derivation:
    @property
    def weight(self) -> float: ...
    @property
    def score(self) -> float: ...
    @property
    def tree(self) -> Tree: ...
    def interpret(self) -> dict[str, str | Tree | FeatureStructure]: ...
    def encode(self, interpretation: str, codec: str) -> str: ...
